# **Desafio Final**

O código abaixo responde as questões de 1 a 9 deste Desafio Final.
As questões de 10 a 15 foram implementadas no código PyCharm utilizando Flask. (projeto desafio-final).

**Enunciando no arquivo: Enunciado do Desafio Final – Desenvolvedor Python.pdf**

**Pergunta 1**
Sobre as quantidades de instâncias e características presentes no dataset, é CORRETO afirmar:
*Existem 768 instâncias e 9 características.*

**Pergunta 2**
Considerando apenas a carta utilizando o módulo pandas, quantos tipos de dados diferentes existem no dataset?
*2 tipos diferentes de dados.* 

**Pergunta 3**
Qual é a idade (coluna 7) média dos pacientes que são diabéticos (coluna 8=1)?
*37,06 anos.* 

**Pergunta 4**
Dentre os pacientes que NÃO tiveram diabetes (coluna 8 =0), qual é o número máximo de gestações (coluna 0) existentes?
*13.* 

**Pergunta 5**
Qual é a afirmação CORRETA sobre o valor 3,0 para a característica número de gestações (coluna 0)?
*Indica que 50% dos valores presentes nessa coluna são maiores que 3.*

**Pergunta 6**
Antes de normalizar, qual é o valor da mediana presente na coluna concentração de glicose (coluna 1)? 
*117.* 

**Pergunta 7**
Dentre as afirmações abaixo, qual está INCORRETA sobre o módulo pandas em python?
*A criação dos dataframes só ocorre quando é utilizado o comando pandas.read_csv().*

**Pergunta 8**
Após dividir as colunas do dataframe entre entrada e saída, aplicar a normalização dos dados como apresentado no enunciado (MinMaxScaler()) e dividir esses dados entre treinamento e teste, aplique o algoritmo KNN. Qual é, aproximadamente, a acurácia do modelo?
*0,68.*

**Pergunta 9**
Após dividir as colunas do dataframe entre entrada e saída, aplicar a normalização dos dados como apresentado no enunciado (MinMaxScaler()) e dividir esses dados entre treinamento e teste, aplique os algoritmos KNN, Árvore de Decisão e MLP. Qual dos algoritmos apresentou maior acurácia?
*MLP.*

**Pergunta 10**
Analisando o código HTML presente neste desafio, o que é INCORRETO dizer sobre a tag HTML <br>?
*Está implementada de maneira equivocada, pois não está acompanhada da tag “end“ <\br>.*

**Pergunta 11**
Sobre o código HTML presente neste desafio, é INCORRETO afirmar:
*Como o HTML trabalha com textos, não é necessário converter as entradas em valores numéricos para serem utilizados no modelo de aprendizado de máquina.*

**Pergunta 12**
Qual é a função das linhas 14 e 18 no código presente na Figura 5?
*Indica qual URL deve chamar a função desejada.*

**Pergunta 13**
Qual é o principal papel das linhas 33 e 34 no código presente na Figura 5? 
*Criar um servidor para receber as requisições.*

**Pergunta 14**
Qual é a ação executada pela linha 23, presente na Figura 5?
*Criar um objeto mutável a partir do mapeamento de um iterable. (A lista é mutável)*

**Pergunta 15**
Qual das alternativas abaixo melhor explica o funcionamento final da junção de todos os códigos presentes neste desafio?
*Capturar dados através de um formulário HTML, aplicar previsão a partir de um modelo e retornar a resposta via web.*

# **Código para responder as questões:**

In [ ]:
#importa as bibliotecas necessárias
import pandas as pd
import matplotlib.pyplot as plt

**O dataset utilizado possui as seguintes colunas**:
0. Número de vezes em que ficou grávida.
1. Concentração de glicose.
2. Pressão diastólica (mm Hg).
3. Espessura da dobra cutânea do tríceps (mm).
4. Insulina (mu U/ml).
5. Índice de massa corporal (peso em kg/(altura em m)^2).
6. Histórico familiar de diabetes.
7. Idade (anos).
8. Classificação (0 ou 1 - 0 não diabético / 1 diabético )

In [ ]:
#leitura dos dados csv e cria o dataframe
df = pd.read_csv("/content/pima-indians-diabetes.csv",header=None,
                 names=["gravidez","glicose","pressão","espessura","insulina","massa","histório","idade","classificação"])
df.head()

gravidez  glicose  pressão  espessura  ...  massa  histório  idade  classificação
0         6      148       72         35  ...   33.6     0.627     50              1
1         1       85       66         29  ...   26.6     0.351     31              0
2         8      183       64          0  ...   23.3     0.672     32              1
3         1       89       66         23  ...   28.1     0.167     21              0
4         0      137       40         35  ...   43.1     2.288     33              1

[5 rows x 9 columns]

In [ ]:
df.shape

(768, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   gravidez       768 non-null    int64  
 1   glicose        768 non-null    int64  
 2   pressão        768 non-null    int64  
 3   espessura      768 non-null    int64  
 4   insulina       768 non-null    int64  
 5   massa          768 non-null    float64
 6   histório       768 non-null    float64
 7   idade          768 non-null    int64  
 8   classificação  768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
# estatísticas básicas
df.describe()

gravidez     glicose  ...       idade  classificação
count  768.000000  768.000000  ...  768.000000     768.000000
mean     3.845052  120.894531  ...   33.240885       0.348958
std      3.369578   31.972618  ...   11.760232       0.476951
min      0.000000    0.000000  ...   21.000000       0.000000
25%      1.000000   99.000000  ...   24.000000       0.000000
50%      3.000000  117.000000  ...   29.000000       0.000000
75%      6.000000  140.250000  ...   41.000000       1.000000
max     17.000000  199.000000  ...   81.000000       1.000000

[8 rows x 9 columns]

In [ ]:
cond = df['classificação'] == 1
df[cond].mean()

gravidez           4.865672
glicose          141.257463
pressão           70.824627
espessura         22.164179
insulina         100.335821
massa             35.142537
histório           0.550500
idade             37.067164
classificação      1.000000
dtype: float64

In [ ]:
cond = df['classificação'] == 1
df[cond].loc[:, 'idade'].mean()

37.06716417910448

In [ ]:
cond = df['classificação'] == 0
df[cond].max()

gravidez          13.000
glicose          197.000
pressão          122.000
espessura         60.000
insulina         744.000
massa             57.300
histório           2.329
idade             81.000
classificação      0.000
dtype: float64

In [ ]:
cond = df['classificação'] == 0
df[cond].loc[:, 'gravidez'].max()

13

In [ ]:
df.loc[:, 'glicose'].median()

117.0

In [ ]:
print(pd.Series(df['gravidez']))
print(type(pd.Series(df['gravidez'])))

0       6
1       1
2       8
3       1
4       0
       ..
763    10
764     2
765     5
766     1
767     1
Name: gravidez, Length: 768, dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
#transforma os dados em array
entradas = df.iloc[:, :-1].values  #dados de entrada
saida = df.iloc[:, -1].values  #saídas ou target
print(entradas)
#print(saida)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


In [ ]:
# realiza o processo de normalização dos dados
from sklearn.preprocessing import MinMaxScaler
normaliza = MinMaxScaler() #objeto para a normalização
#entradas_normalizadas
entradas_normalizadas = normaliza.fit_transform(entradas) #realiza a normalização dos dados

In [ ]:
#realiza a divisão dos dados entre treinamento e teste
from sklearn.model_selection import train_test_split # função que realiza a divisão do dataset
# divide 30% para teste
x_train, x_test, y_train, y_test = train_test_split(entradas_normalizadas, saida, test_size=0.30, random_state=42)

**Algoritmo KNN:** clf_KNN bold text = KNeighborsClassifier(n_neighbors=5)

In [ ]:
#treina o modelo
from sklearn.neighbors import KNeighborsClassifier
clf_KNN = KNeighborsClassifier(n_neighbors=5) #utiliza a construção por meio de 5 vizinhos
clf_KNN.fit(x_train, y_train) # Realiza o treinamento do classificador

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
#Realiza a previsão de classificaçao
y_pred_KNN = clf_KNN.predict(x_test)

In [ ]:
#constroi a matriz de confusão para comparar o modelo criado
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_KNN))
print(classification_report(y_test, y_pred_KNN))

[[118  33]
 [ 41  39]]
              precision    recall  f1-score   support

           0       0.74      0.78      0.76       151
           1       0.54      0.49      0.51        80

    accuracy                           0.68       231
   macro avg       0.64      0.63      0.64       231
weighted avg       0.67      0.68      0.68       231



In [ ]:
from sklearn.metrics import accuracy_score
acuracia_KNN = accuracy_score(y_test, y_pred_KNN)
print('Acurácia KNN: ',acuracia_KNN)

Acurácia KNN:  0.6796536796536796


**Algoritmo Árvore de Decisão:** clf_arvore = DecisionTreeClassifier(random_state=1)

In [ ]:
#treina o modelo
from sklearn.tree import DecisionTreeClassifier # importa o classificador árvore de decisão
clf_arvore = DecisionTreeClassifier(random_state=1)
clf_arvore.fit(x_train,y_train) # Realiza o treinamento do classificador

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1, splitter='best')

In [ ]:
#Realiza a previsão de classificaçao 
y_pred_arvore = clf_arvore.predict(x_test)

In [ ]:
#constroi a matriz de confusão para comparar o modelo criado
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_arvore))
print(classification_report(y_test, y_pred_arvore))

[[106  45]
 [ 25  55]]
              precision    recall  f1-score   support

           0       0.81      0.70      0.75       151
           1       0.55      0.69      0.61        80

    accuracy                           0.70       231
   macro avg       0.68      0.69      0.68       231
weighted avg       0.72      0.70      0.70       231



In [ ]:
from sklearn.metrics import accuracy_score
acuracia_arvore = accuracy_score(y_test, y_pred_arvore)
print('Acurácia da árvore de Decisão: ',acuracia_arvore)

Acurácia da árvore de Decisão:  0.696969696969697


**Algoritmo Rede MLP :**
clf_mlp = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5,
10), random_state=1)

In [ ]:
#treina o modelo
from sklearn.neural_network import MLPClassifier # importa o classificador Redes Neurais (MLP)
clf_mlp = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 10), random_state=1)
clf_mlp.fit(x_train,y_train) # Realiza o treinamento do classificador

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(5, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [ ]:
#Realiza a previsão de classificaçao 
y_pred_mlp = clf_mlp.predict(x_test)

In [ ]:
#constroi a matriz de confusão para comparar o modelo criado
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_mlp))
print(classification_report(y_test, y_pred_mlp))

[[124  27]
 [ 32  48]]
              precision    recall  f1-score   support

           0       0.79      0.82      0.81       151
           1       0.64      0.60      0.62        80

    accuracy                           0.74       231
   macro avg       0.72      0.71      0.71       231
weighted avg       0.74      0.74      0.74       231



In [ ]:
from sklearn.metrics import accuracy_score
acuracia_MLP = accuracy_score(y_test, y_pred_mlp)
print('Acurácia da Rede MLP: ',acuracia_MLP)

Acurácia da Rede MLP:  0.7445887445887446


In [ ]:
if (acuracia_KNN > acuracia_arvore) & (acuracia_KNN > acuracia_MLP):
  print('Acurácia KNN é maior.')
elif (acuracia_arvore > acuracia_KNN) & (acuracia_arvore > acuracia_MLP):
  print('Acurácia Árvore de Decisão é maior.')
else:
  print('Acurácia Rede MLP é maior.')


Acurácia Rede MLP é maior.


In [ ]:
import joblib
import numpy as np

In [ ]:
# Salvando o modelo no disco.
# melhor_modelo: modelo com melhor acurácia.
# nome_do_arquivo: caminho do local onde deve ser salvo o modelo.
nome_do_arquivo = 'melhor_modelo.sav' # observe a extensao .sav

if (acuracia_KNN > acuracia_arvore) & (acuracia_KNN > acuracia_MLP):
  melhor_modelo = clf_KNN
elif (acuracia_arvore > acuracia_KNN) & (acuracia_arvore > acuracia_MLP):
  melhor_modelo = clf_arvore
else:
  melhor_modelo = clf_mlp

joblib.dump(melhor_modelo, nome_do_arquivo) 

['melhor_modelo.sav']

In [ ]:
# carregando o modelo salvo
modelo_salvo = joblib.load(nome_do_arquivo) # realiza a carga do modelo salvo

In [ ]:
lista_valores = np.array([1., 85.,66.,29.,0.,26.6,351.,31.]) # atenção, considerar todos float
prever = lista_valores.reshape(1,8)
resultado = modelo_salvo.predict(prever)
if resultado[0] == 0:
  print('0 não diabético')
else:
  print('1 diabético')

lista_valores = np.array([6.,148.,72.,35.,0.,33.6,0.627,50.]) # atenção, considerar todos float 
prever = lista_valores.reshape(1,8)
resultado = modelo_salvo.predict(prever)
if resultado[0] == 0:
  print('0 não diabético')
else:
  print('1 diabético')


0 não diabético
1 diabético


In [ ]:
?map()

https://scikit-learn.org/stable/modules/model_persistence.html